config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "homes#top", as: "root"
  post '/homes/guest_sign_in' => 'homes#guest_sign_in'
  patch "/users/:id/secession" => "users#secession", as: "secession"



  resources :users, only:[:show, :edit, :update]
  
  get "search" => "searches#search"
  get "my_group" => "groups#my_group"
  get "quick_form" => "users#quick_form"
  post "all_create" => "targets#all_create"

  resources :groups do
    resources :group_members, only: [:create, :destroy, :index] do
      member do
        post :direct
      end
    end
    resources :entries, only: [:create, :index, :destroy]
    resources :targets, only: [:create, :edit, :update, :destroy] do

    end
    resources :results, only: [:create, :edit, :update, :destroy]
    resources :group_messages, only: [:create, :destroy]
    resources :stamps, only: [:create, :destroy]
  end

  resources :contacts, only: [:new, :create]
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :group, optional: true

  validates :user_id, presence: true
  validates :group_id, presence: true
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, only:[:index]

  # indexで、グループの操作権限がない場合の処理(operation_right = 0の場合)
  def ensure_current_user
    unless GroupMember.find_by(user_id: current_user.id, group_id: params[:group_id], operation_right: 1).present?
      flash[:alert] = "閲覧権限がありません！"
      redirect_to user_path(current_user)
    end
  end


  def create
    # 送信者のid、ページのグループidを取得し、加入申請として保存
    entry = Entry.new(entry_params)
    entry.user_id = current_user.id
    entry.group_id = params[:group_id]
    entry.save
    flash[:notice] = "加入申請を送りました！"
    redirect_to request.referer
  end

  def destroy
    # 申請却下、取り下げの場合はこちらを実行
    @entry = Entry.find_by(group_id: params[:group_id], id: params[:id])
    @entry.destroy
    redirect_to request.referer
  end

  def index
    @entries = Entry.where(group_id: params[:group_id])
    @group = Group.find(params[:group_id])
    @group_member = GroupMember.new
  end

  private

  def entry_params
    params.permit(:user_id, :group_id)
  end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<div class="entry_index">
  <h3>グループ加入申請一覧</h3>
  <% if @entries.count == 0 %>
    <div class="nothing">加入申請はありません</div>
  <%else%>
    <table class="borderless_table">
      <thead>
        <tr>
          <th class="th1">ユーザー画像</th><th class="th2">名前</th><th class="th3"></th>
        </tr>
      </thead>
      <tbody>
        <% @entries.each do |entry| %>
          <tr>
            <td class="td1"><%= attachment_image_tag entry.user, :image, format: "jpeg", size: "100x100", class: "image", fallback: "user.png" %></td>
            <td class="td2"><%= entry.user.name %></td>
            <td class="td3">
              <%= form_with(model:[@group, @group_member], local:true) do |f| %>
                <div class="action">
                  <%= hidden_field_tag :user_id, entry.user_id %>
                  <%= f.submit "許可", class: "big_btn" %>
                </div>
              <%end%>
              <%= link_to group_entry_path(@group, entry.id), method: :delete, data: {confirm: "このユーザーの加入申請を破棄します。よろしいですか？"}, class: "edit_link" do %>
                <div class="red_btn">却下</div>
              <%end%>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  <%end%>
</div>