config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "homes#top", as: "root"
  post '/homes/guest_sign_in' => 'homes#guest_sign_in'
  patch "/users/:id/secession" => "users#secession", as: "secession"



  resources :users, only:[:show, :edit, :update]
  
  get "search" => "searches#search"
  get "my_group" => "groups#my_group"
  get "quick_form" => "users#quick_form"
  post "all_create" => "targets#all_create"

  resources :groups do
    resources :group_members, only: [:create, :destroy, :index] do
      member do
        post :direct
      end
    end
    resources :entries, only: [:create, :index, :destroy]
    resources :targets, only: [:create, :edit, :update, :destroy] do

    end
    resources :results, only: [:create, :edit, :update, :destroy]
    resources :group_messages, only: [:create, :destroy]
    resources :stamps, only: [:create, :destroy]
  end

  resources :contacts, only: [:new, :create]
end

app/models/group.rb
class Group < ApplicationRecord
  attachment :image
  enum group_type: {"work_group": 0, "friend_group": 1}
  validates :name, presence: true
  validates :group_type, presence: true

  has_many :group_members, dependent: :destroy
  has_many :users, through: :group_members
  has_many :entries, dependent: :destroy
  has_many :targets, dependent: :destroy
  has_many :group_messages, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :stamps, dependent: :destroy



  def user_exists?(user, group)
    group_members.where(user_id: user.id, group_id: group.id).present?
  end

  # 検索機能、名前が一致している部分があるgroupを返す
  def self.looks(word)
    @user = Group.where("name LIKE?","%#{word}%")
  end

  def entry_exists?(user)
    self.entries.find_by(group_id: self.id, user_id: user.id)
  end


  # users/quick_formにて使用
  def today_my_target_exists?(user)
    self.targets.find_by(user_id: user, created_at: Time.zone.now.all_day).present?
  end

  def today_my_target(user)
    self.targets.find_by(user_id: user, created_at: Time.zone.now.all_day)
  end

  def today_my_result_exists?(user)
    self.results.find_by(user_id: user, created_at: Time.zone.now.all_day).present?
  end

  def today_my_result(user)
    self.results.find_by(user_id: user, created_at: Time.zone.now.all_day)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, only:[:edit, :update]
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # showで、グループの操作権限がない場合の処理(operation_right = 0の場合)
  def ensure_current_user
    unless GroupMember.find_by(user_id: current_user.id, group_id: params[:id], operation_right: 1).present?
      flash[:alert] = "閲覧権限がありません！"
      redirect_to user_path(current_user)
    end
  end

  def index
    @groups = Group.all.page(params[:page]).per(10)
  end

  def show
    # 共通するインスタンス変数
    @my_group_status = @group.group_members.find_by(group_id: @group, user_id: current_user.id)
    @entry = Entry.new
    @direct_join = GroupMember.new

    # workグループ
    @target = Target.new
    @result = Result.new
    @today_targets = @group.targets.where(created_at: Time.zone.now.all_day).page(params[:page]).per(10)
    @today_my_target = @today_targets.where(user_id: current_user.id).count

    # グラフ部分(chart.js)
    graph_datas = @group.results.where(created_at: Time.zone.now.all_day).order(:achievement).last(7)
    # graph_datasの順で、下のラベルに名前を入力させるための処理
    graph_labels = []
    graph_datas.each do |g|
      user = User.find(g.user_id)
      graph_labels << user.name
    end
    # graph_labelsが6個以下の場合、配列の合計数が7個になるように処理
    empties = 7 - graph_labels.size
    if empties > 0
      empties.times do
        graph_labels << "no_data"
      end
    end
    # groups.coffeeに受け渡す部分
    gon.datas = graph_datas.pluck(:achievement)
    gon.labels = graph_labels

    # friendグループ
    @message = GroupMessage.new
    @messages = GroupMessage.where(group_id: @group.id).order(id: "desc").page(params[:page]).per(15)
    @stamp = Stamp.new
  end

  def new
    @group = Group.new
    @group_member = GroupMember.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      # グループ作成者をグループメンバーに含める処理
      @direct_join = GroupMember.new(group_member_params)
      @direct_join.user_id = current_user.id
      @direct_join.group_id = @group.id
      @direct_join.operation_right = 1
      @direct_join.save
      flash[:notice] = "グループを作成しました！"
      redirect_to group_path(@group.id)
    else
      flash.now[:alert] = "必要な情報を入力してください！"
      render "new"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      flash[:notice] = "グループ情報を変更しました！"
      redirect_to group_path(@group.id)
    else
      flash.now[:alert] = "情報の変更に失敗しました！"
      render "edit"
    end
  end

  def destroy
    @group.destroy
    flash[:notice] = "グループの削除が完了しました！"
    redirect_to user_path(current_user.id)
  end

  def my_group
    @my_groups = current_user.groups.page(params[:page]).per(10)
  end


  private

  def group_params
    params.require(:group).permit(:name, :intro, :image, :group_type, :direct_join)
  end

  def group_member_params
    params.permit(:user_id, :group_id, :operation_right)
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_friend.html.erb
<div class="friend">
  <h3>フレンドグループ</h3>
  <!--閲覧者がこのグループのメンバーでない場合、グループ詳細を表示しない-->
  <%if @group.user_exists?(current_user, @group) %>
  <div class="comment">
    <%= form_with(model: [@group, @message], local: true) do |f| %>

      <div class="area">
        <%= f.text_area :message, placeholder: "投稿内容を記入してください", class: "text_area"%>
      </div>

      <div class="action">
        <%= f.submit "掲示板に投稿", class: "big_btn" %>
      </div>
    <%end%>
  </div>

  <div class="messages">
    <% @messages.each do |msg| %>
      <div class="content">

        <div class="icon">
          <%= attachment_image_tag msg.user, :image, format: "jpeg", size: "70x70", class: "image", fallback: "user.png"%>
          <div class="name">
            <%= msg.user.name %>
          </div>
        </div>

        <!--google感情分析API、スコアによって背景色が変わる-->
        <% if msg.score >= 0.2 %>
          <div class="happy_text">
            <%= msg.message %>
          </div>
        <% elsif msg.score <= -0.4 %>
          <div class="sad_text">
            <%= msg.message %>
          </div>
        <%else%>
          <div class="text">
            <%= msg.message %>
          </div>
        <%end%>

        <div class="reaction">
          <div class="time"><%= l msg.created_at, format: :short %></div>

          <div id="stamp_id_<%= msg.id %>">
            <%= render 'groups/stamp', msg: msg %>
          </div>


          <% if msg.user_id == current_user.id %>
            <%= link_to group_group_message_path(@group, msg), method: :delete, class: "edit_link" do %>
              <div class="red_btn">削除</div>
            <%end%>
          <%end%>

        </div>

      </div>
    <%end%>
    <div class="paginate"><%= paginate @messages %></div>

    <div class="leave">
      <% if @my_group_status.operation_right == 0 %>
        <%= link_to group_group_member_path(@group, current_user.id), method: :delete, data: {confirm: "このグループを退会します。本当によろしいですか？"}, class: "edit_link" do %>
          <button class="red_btn">グループ退会</button>
        <%end%>
      <%else%>
        ＊グループ作成者は退会不可能です。「情報変更」から、グループ削除をご利用ください。
      <%end%>
    </div>
  </div>



  <%else%>
  <!--このグループのメンバーでない場合の表示-->
  <div class="join">
    <div>メンバーではないため、情報を閲覧することができません！</div>
    <% if @group.direct_join == true %>
      <div class="action">
        <%= form_with(url: direct_group_group_member_path(@group.id), model:[@group, @direct_join], local: true) do |f| %>
          <%= f.submit "加入", class: "big_btn" %>
        <%end%>
        <div>＊すぐに加入できます！</div>
      </div>


    <%else%>
      <!--加入申請がすでに送られている場合は、加入申請を送れない-->
      <% unless @group.entry_exists?(current_user) %>
        <%= form_with(model:[@group, @entry], local: true) do |f| %>
          <div class="action">
            <%= f.submit "加入", class: "big_btn" %>
            <div>＊加入申請を送信します！</div>
          </div>
        <%end%>
      <%else%>
        <div>申請を送りました！承諾された場合、グループを利用することができます！</div>
      <%end%>
    <%end%>
  </div>
  <%end%>
</div>

app/views/groups/_stamp.html.erb
<div class="stamp">
  <div>
    <% if msg.stamp_exists?(current_user.id, msg.id) %>
      <% if msg.stamp1_exists?(current_user.id, msg.id) %>
        <%= link_to group_stamp_path(@group.id, msg.id, choose_stamp: 1, message_id: msg.id), method: :delete, remote: true do %>
          <div class="true_stamp_1"></div><%= msg.stamp_count1.count %>
        <%end%>
      <% else %>
        <div class="stamp_1"></div><%= msg.stamp_count1.count %>
      <%end%>
    <%else%>
      <%= form_with(model: [@group, @stamp]) do |f| %>
        <%= f.hidden_field :choose_stamp, :value => 1 %>
        <%= hidden_field_tag :message_id, msg.id %>
        <%= f.submit class: "stamp_1" %><div><%= msg.stamp_count1.count %></div>
      <%end%>
    <%end%>
  </div>

  <div>
    <% if msg.stamp_exists?(current_user.id, msg.id) %>
      <% if msg.stamp2_exists?(current_user.id, msg.id) %>
        <%= link_to group_stamp_path(@group.id, msg.id, choose_stamp: 2, message_id: msg.id), method: :delete, remote: true do %>
          <div class="true_stamp_2"></div><%= msg.stamp_count2.count %>
        <%end%>
      <% else %>
        <div class="stamp_2"></div><%= msg.stamp_count2.count %>
      <%end%>
    <%else%>
      <%= form_with(model: [@group, @stamp]) do |f| %>
        <%= f.hidden_field :choose_stamp, :value => 2 %>
        <%= hidden_field_tag :message_id, msg.id %>
        <%= f.submit class: "stamp_2" %><div><%= msg.stamp_count2.count %></div>
      <%end%>
    <%end%>
  </div>

  <div>
    <% if msg.stamp_exists?(current_user.id, msg.id) %>
      <% if msg.stamp3_exists?(current_user.id, msg.id) %>
        <%= link_to group_stamp_path(@group.id, msg.id, choose_stamp: 3, message_id: msg.id), method: :delete, remote: true do %>
          <div class="true_stamp_3"></div><%= msg.stamp_count3.count %>
        <%end%>
      <% else %>
        <div class="stamp_3"></div><%= msg.stamp_count3.count %>
      <%end%>
    <%else%>
      <%= form_with(model: [@group, @stamp]) do |f| %>
        <%= f.hidden_field :choose_stamp, :value => 3 %>
        <%= hidden_field_tag :message_id, msg.id %>
        <%= f.submit class: "stamp_3" %><div><%= msg.stamp_count3.count %></div>
      <%end%>
    <%end%>
  </div>
</div>

app/views/groups/_work.html.erb
<div class="work">
  <%if @group.user_exists?(current_user, @group) %>
    <h3>データ</h3>
    <div class="data">
      <% if @today_my_target == 0 %>
        <%= form_with(model: [@group, @target], local: true) do |f| %>

          <div class="area">
            <div>一日一回、記入してください！</div>
            <%= f.text_area :target_content, placeholder: "今日の目標を一言！", class: "text_area", id: "session_target" %>
          </div>

          <div class="field">
            <%= f.submit "今日の目標登録", class: "big_btn" %>
          </div>
        <%end%>
      <%else%>
        <div>今日の目標は記入済みです！</div>
      <%end%>
    </div>

    <div class="target">
      <h1>今日の目標</h1>
      <table border="1">
        <thead>
          <tr>
            <th>ユーザーネーム</th><th>目標</th><th>達成%</th>
          </tr>
        </thead>
        <tbody>
          <% @today_targets.each do |target| %>
            <tr>
              <td><%= attachment_image_tag target.user, :image, format: "jpeg", size: "50x50", class: "image", fallback: "user.png" %><br><%= target.user.name %></td>
              <td>
                <% if target.user_id == current_user.id %>
                  <%= link_to target.target_content, edit_group_target_path(@group, target.id) %>
                <%else%>
                  <%= target.target_content %>
                <%end%>
              </td>
              <td>
                <!--リザルトが投稿されているか、未投稿ならそれは自分のtargetかの確認-->
                <% if target.achievement_exists?(target, current_user.id) == "my_result" %>

                  <!--リザルト投稿済み＆自分の投稿で、editリンクを表示-->
                  <%= link_to target.result.achievement, edit_group_result_path(@group, target.result.id) %>

                <% elsif target.achievement_exists?(target, current_user.id) == "someones_result" %>
                  <!--誰かのリザルトである場合、数値のみを表示-->
                  <%= target.result.achievement %>

                <% elsif target.achievement_exists?(target, current_user.id) == "my_target_yet_result" %>
                  <!--リザルト未投稿、かつ自分のtargetである場合-->
                  <%= form_with(model: [@group, @result], local: true) do |f| %>
                    <div class="area">
                      <%= f.text_field :achievement, placeholder: "0~100", id: "session_result" %>
                    </div>
                    <div class="field">
                      <%= f.submit "登録" %>
                    </div>
                  <%end%>

                <% elsif target.achievement_exists?(target, current_user.id) == "someones_target_yet_result" %>
                  <!--リザルト未投稿、かつ誰かのtargetである場合-->
                  <div>未記入</div>
                <%end%>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>

    <div class="memo">
      <h3>今日の取り組み結果メモ</h3>
      <table border="1">
        <thead>
          <tr>
            <th>ユーザーネーム</th>
            <th>取り組み結果メモ</th>
          </tr>
        </thead>
        <tbody>
          <% @today_targets.each do |target| %>
            <tr>
              <td><%= attachment_image_tag target.user, :image, format: "jpeg", size: "50x50", class: "image", fallback: "user.png" %><br><%= target.user.name %></td>
              <td>
                <% if target.result_memo_exists?(target) %>
                  <%= target.result.result_memo %>
                <%else%>
                  (メモはありません)
                <%end%>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>

    <dev class="paginate"><%= paginate @today_targets %></dev>

    <div class="graph">
      <h3>今日の達成度比較</h3>
      <% if false %>
        <%= column_chart @results.pluck(:created_at, :achievement), class: "graph_size" %>
      <%end%>
      <canvas id="myChart" width="200" height="100"></canvas>
      <script>draw_graph();</script>
    </div>

    <!--このグループで、自分の編集ステータスがない場合、退会ボタンを表示-->
    <div class="leave">
      <% if @my_group_status.operation_right == 0 %>
        <%= link_to group_group_member_path(@group, current_user.id), method: :delete, data: {confirm: "このグループを退会します。本当によろしいですか？"}, class: "edit_link" do %>
          <button class="red_btn">グループ退会</button>
        <%end%>
      <%else%>
        ＊グループ作成者は退会不可能です。「情報変更」から、グループ削除をご利用ください。
      <%end%>
    </div>


  <%else%>
  <!--このグループのメンバーでない場合の表示-->
  <div class="join">
    <div>メンバーではないため、情報を閲覧することができません！</div>
    <% if @group.direct_join == true %>
      <div class="action">
        <%= form_with(url: direct_group_group_member_path(@group.id), model:[@group, @direct_join], local: true) do |f| %>
          <%= f.submit "加入", class: "big_btn" %>
        <%end%>
        <div>＊すぐに加入できます！</div>
      </div>


    <%else%>
      <!--加入申請がすでに送られている場合は、加入申請を送れない-->
      <% unless @group.entry_exists?(current_user) %>
        <%= form_with(model:[@group, @entry], local: true) do |f| %>
          <div class="action">
            <%= f.submit "加入", class: "big_btn" %>
            <div>＊加入申請を送信します！</div>
          </div>
        <%end%>
      <%else%>
        <div>申請を送りました！承諾された場合、グループを利用することができます！</div>
      <%end%>
    <%end%>
  </div>
  <%end%>
</div

app/views/groups/edit.html.erb
<h3>グループ変更</h3>
<div class="text_form">

  <%= form_with model: @group, local: true do |f| %>

    <div class="field">
      <%= f.label :name, "グループ名" %>
      <%= f.text_field :name, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :intro, "グループ紹介" %>
      <%= f.text_area :intro, class: "text_area" %>
    </div>

    <div class="field">
      <%= f.label :image, "グループ画像（任意）" %>
      <%= f.attachment_field :image %>
    </div>

    <div class="field">
      <h3>*グループタイプの変更はできません</h3>
    </div>

    <div><strong>グループ加入の際</strong></div><br>
    <div class="field">
      <%= f.label :direct_join, "申請が必要", value: "false" %>
      <%= f.radio_button :direct_join, "false", checked: true %><br>

      <%= f.label :direct_join, "申請は不要", value: "true" %>
      <%= f.radio_button :direct_join, "true" %>
    </div>

    <div class="action">
      <%= f.submit "グループ変更", class: "big_btn" %>
    </div>

  <%end%>

  <%= link_to group_path(@group.id), method: :delete, data: {confirm: "グループを削除した場合、元に戻すことはできません。本当によろしいですか？"}, class: "edit_link" do %>
    <div class="red_btn">グループを削除</div>
  <%end%>


</div>

app/views/groups/index.html.erb
<div class="group_index">
  <h3>グループ一覧</h3>
  <table class="borderless_table">
    <thead>
      <tr>
        <th class="th1">グループ画像</th><th class="th2">名前</th><th class="th3">メンバー数</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td class="td1">
            <% if group.group_type == "work_group" %>
              <%= attachment_image_tag group, :image, format: "jpeg", size: "150x150", class: "image", fallback: "work.png" %>
            <% elsif group.group_type == "friend_group" %>
              <%= attachment_image_tag group, :image, format: "jpeg", size: "150x150", class: "image", fallback: "friend.png" %>
            <%end%>
          </td>
          <td class="td2"><%= link_to group.name, group_path(group.id) %></td>
          <td class="td3"><%= group.group_members.count %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <div class="paginate"><%= paginate @groups %></div>
</div>

app/views/groups/my_group.html.erb
<div class="group_index">
  <h3>所属しているグループ一覧</h3>
  <table class="borderless_table">
    <thead>
      <tr>
        <th class="th1">グループ画像</th><th class="th2">名前</th><th class="th3">メンバー数</th>
      </tr>
    </thead>
    <tbody>
      <% @my_groups.each do |group| %>
        <tr>
          <td class="td1">
            <% if group.group_type == "work_group" %>
              <%= attachment_image_tag group, :image, format: "jpeg", size: "150x150", class: "image", fallback: "work.png" %>
            <% elsif group.group_type == "friend_group" %>
              <%= attachment_image_tag group, :image, format: "jpeg", size: "150x150", class: "image", fallback: "friend.png" %>
            <%end%>
          </td>
          <td class="td2"><%= link_to group.name, group_path(group.id) %></td>
          <td class="td3"><%= group.group_members.count %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
<div class="paginate"><%= paginate @my_groups %></div>

app/views/groups/new.html.erb
<div class="text_form">

  <h2>グループ新規作成</h2>

  <%= form_with model: @group, local: true do |f| %>

    <div class="field">
      <%= f.label :name, "グループ名" %>
      <%= f.text_field :name, autofocus: true, id: "session_name" %>
    </div>

    <div class="field">
      <%= f.label :intro, "グループ紹介" %>
      <%= f.text_area :intro, id: "session_intro" %>
    </div>

    <div class="field">
      <%= f.label :image, "グループ画像（任意）" %>
      <%= f.attachment_field :image, id: "session_image" %>
    </div>

    <div class="field">
      <%= f.label :group_type, "ワークグループ", value: "work_group" %>
      <%= f.radio_button :group_type, "work_group", checked: true, id: "session_work_group" %><br>

      <%= f.label :group_type, "フレンドグループ", value: "friend_group" %>
      <%= f.radio_button :group_type, "friend_group", id: "session_friend_group" %>
    </div>

    <div><strong>グループ加入の際</strong></div><br>
    <div class="field">
      <%= f.label :direct_join, "申請が必要", value: "false" %>
      <%= f.radio_button :direct_join, "false", checked: true, id: "session_direct_false" %><br>

      <%= f.label :direct_join, "申請は不要", value: "true" %>
      <%= f.radio_button :direct_join, "true", id: "session_direct_true" %>
    </div>

    <div class="action">
      <%= f.submit "グループ作成", class: "big_btn" %>
    </div>

  <%end%>

</div>

app/views/groups/show.html.erb
<div class="container group_show">

  <div class="info">

    <h3>グループ情報</h3>

    <div class="type">
      <%= @group.group_type %>
    </div>
    <% if @group.group_type == "work_group" %>
      <%= attachment_image_tag @group, :image, format: "jpeg", size: "150x150", class: "image", fallback: "work.png" %>
    <% elsif @group.group_type == "friend_group" %>
      <%= attachment_image_tag @group, :image, format: "jpeg", size: "150x150", class: "image", fallback: "friend.png" %>
    <%end%>


    <div class="name">
      NAME<br><%= @group.name %>
    </div>

    <div class="intro">
      INTRO<br>
      <%= @group.intro %>
    </div>

    <%= link_to group_group_members_path(@group.id), class: "edit_link" do %>
      <div class="green_btn">メンバー一覧</div>
    <%end%>

    <% if @group.user_exists?(current_user, @group) && @my_group_status.operation_right == 1 %>
      <%= link_to group_entries_path(@group.id), class: "edit_link" do %>
        <% if @group.entries.count == 0 %>
          <div class="green_btn">加入申請一覧</div>
        <%else%>
          <div class="red_btn">(新着あり)加入申請</div>
        <%end%>
      <%end%>

      <%= link_to edit_group_path, class: "edit_link" do %>
        <div class="green_btn">情報変更</div>
      <%end%>
    <%end%>


  </div>

  <div class="main">
    <% if @group.group_type == "work_group" %>
      <%= render 'groups/work' %>
    <% elsif @group.group_type == "friend_group" %>
      <%= render 'groups/friend' %>
    <%end%>
  </div>
</div>