config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "homes#top", as: "root"
  post '/homes/guest_sign_in' => 'homes#guest_sign_in'
  patch "/users/:id/secession" => "users#secession", as: "secession"



  resources :users, only:[:show, :edit, :update]
  
  get "search" => "searches#search"
  get "my_group" => "groups#my_group"
  get "quick_form" => "users#quick_form"
  post "all_create" => "targets#all_create"

  resources :groups do
    resources :group_members, only: [:create, :destroy, :index] do
      member do
        post :direct
      end
    end
    resources :entries, only: [:create, :index, :destroy]
    resources :targets, only: [:create, :edit, :update, :destroy] do

    end
    resources :results, only: [:create, :edit, :update, :destroy]
    resources :group_messages, only: [:create, :destroy]
    resources :stamps, only: [:create, :destroy]
  end

  resources :contacts, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  validates :email, presence: true
  validates :name, presence: true, length: { maximum: 10 }
  validates :intro, length: { maximum: 50 }


  has_many :group_members, dependent: :destroy
  has_many :groups, through: :group_members
  has_many :entry, dependent: :destroy
  has_many :targets, dependent: :destroy
  has_many :group_messages, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :stamps, dependent: :destroy


  # 検索機能、名前が一致している部分があるuserを返す
  def self.looks(word)
    @user = User.where("name LIKE?","%#{word}%")
  end

  # 退会ユーザー利用不可処理で用いる
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  # 退会後のユーザーはログインできないようにする
  def reject_inactive_user
    @user = User.find_by(name: params[:user][:name])
    if @user
      if @user.valid_password?(params[:user][:password]) && !@user.is_deleted
        redirect_to new_user_session_path
      end
    end
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, only:[:edit, :update]

  # current_userが関連しないページへのアクセスを制限する処理
  def ensure_current_user
    if current_user.id != params[:id].to_i
      flash[:alert] = "閲覧権限がありません！"
      redirect_to user_path(current_user)
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:notice] = "変更を保存しました！"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "変更に失敗しました！"
      render "edit"
    end
  end

  def show
    @user = User.find(current_user.id)
    @target = Target.new
    @group_ranks = Group.find(GroupMember.group(:group_id).order("count(group_id) desc").limit(3).pluck(:group_id))
  end

  def quick_form
    @my_groups = current_user.groups.where(group_type: "work_group").page(params[:page]).per(10)
    @new_target = Target.new
    @result = Result.new
  end

  # 退会処理
  def secession
    user = User.find(params[:id])
    user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理が完了しました。ご利用ありがとうございました！"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :intro, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="text_form">
  <h3>ユーザー情報変更</h3>
  <%= form_with model: @user, local: true do |f| %>

    <%= render 'layouts/error_messages', object: f.object %>

    <div class="field">
      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :intro, "自己紹介" %>
      <%= f.text_area :intro, class: "text_area" %>
    </div>

    <div class="field">
      <%= f.label :image, "ユーザー画像（任意）" %>
      <%= f.attachment_field :image %>
    </div>

    <div class="action">
      <%= f.submit "ユーザー変更", class: "big_btn" %>
    </div>

  <%end%>

  <%= link_to secession_path(@user.id), method: :patch, data: {confirm: "退会した場合、このアカウントは二度と使えなくなります。本当によろしいですか？"}, class: "edit_link" do %>
    <button class="red_btn">退会</button>
  <%end%>

</div>

app/views/users/quick_form.html.erb
<div class="quick_form">
  <h3>ワークグループ<br>クイック投稿フォーム</h3>
  <table class="borderless_table">

    <thead>
      <tr>
        <th>グループ</th><th>今日の目標</th><th>達成度</th>
      </tr>
    </thead>

    <tbody>
      <% @my_groups.each do |group| %>
        <tr>
          <td>
            <%= link_to group_path(group.id) do %>
              <% if group.group_type == "work_group" %>
                <%= attachment_image_tag group, :image, format: "jpeg", size: "75x75", class: "image", fallback: "work.png" %>
              <% elsif group.group_type == "friend_group" %>
                <%= attachment_image_tag group, :image, format: "jpeg", size: "75x75", class: "image", fallback: "friend.png" %>
              <%end%>
              <br><%= group.name %>
            <%end%>
          </td>

          <td>
            <!--今日のtargetの投稿がなければ、入力フォームを表示-->
            <% if group.today_my_target_exists?(current_user.id) %>
              <%= group.today_my_target(current_user.id).target_content %>
            <%else%>
              <%= form_with(model: [group, @new_target], local: true) do |f| %>
                <div class="area">
                  <%= f.text_area :target_content, placeholder: "今日の目標を一言！", class: "text_area"%>
                </div>

                <div class="field">
                  <%= f.submit "今日の目標登録", class: "big_btn" %>
                </div>
              <%end%>
            <%end%>
          </td>

          <td>
            <% if group.today_my_result_exists?(current_user.id) %>
              <!--今日のresult投稿済みの場合-->
              <%= group.today_my_result(current_user.id).achievement %>
            <% elsif group.today_my_target_exists?(current_user.id) %>
              <!--今日のtarget投稿済み、result未投稿の場合-->
              <%= form_with(model: [group, @result], local: true) do |f| %>

                <div class="field">
                  <%= f.label :achievement, "達成割合（数字のみ）" %>
                  <%= f.text_field :achievement, autofocus: true, placeholder: "0~100" %>
                </div>


                <div class="field">
                  <%= f.label :result_memo, "取組結果のメモ（任意）" %>
                  <%= f.text_area :result_memo, class: "text_area" %>
                </div>

                <div class="action">
                  <%= f.submit "目標変更", class: "big_btn" %>
                </div>

              <%end%>
            <%else%>
              <!--今日のtarget未投稿、result未投稿の場合-->
              <div>今日の目標を投稿していません！</div>
            <%end%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <div class="paginate"><%= paginate @my_groups %></div>
</div>

app/views/users/show.html.erb
<div class="container user_show">
  <div class="info">
    <h3>ユーザー情報</h3>
    <%= attachment_image_tag @user, :image, format: "jpeg", size: "150x150", class: "image", fallback: "user.png" %>
    <div class="name">
      NAME<br>
      <%= @user.name %>
    </div>
    <div class="intro">
      INTRO<br>
      <%= @user.intro %>
    </div>
    <%= link_to edit_user_path, class: "edit_link" do %>
      <div class="green_btn">情報変更</div>
    <%end%>

    <%= form_with url: all_create_path, model: @target, local: true do |f| %>

      <div class="area">
        <div>今日の目標を<br>すべてのグループに投稿！</div>
        <%= f.text_area :target_content, placeholder: "今日の目標を一言！", class: "text_area"%>
      </div>

      <div class="field">
        <%= f.submit "今日の目標登録", class: "big_btn" %>
      </div>
    <%end%>
    <%= link_to "所属するワークグループ", quick_form_path %>
  </div>
  <div class="main">
    <h3>メニュー</h3>

    <div class="group">
      <h3>ユーザーが多いグループ</h3>
      <div class="container">
        <% @group_ranks.each do |group| %>
        <div class="group_rank">
          <%= link_to group_path(group.id) do %>
            <div class="head">
              <% if group.group_type == "work_group" %>
                <%= attachment_image_tag group, :image, format: "jpeg", size: "100x100", class: "image", fallback: "work.png" %>
              <% elsif group.group_type == "friend_group" %>
                <%= attachment_image_tag group, :image, format: "jpeg", size: "100x100", class: "image", fallback: "friend.png" %>
              <%end%>
            </div>
            <div class="name">
              <%= group.name %>
            </div>
            <div class="type">
              <%= group.group_type %>
            </div>
          <%end%>
        </div>
        <%end%>
      </div>

      <div class="search_form">
        <div>検索フォーム</div>
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([["User"], ["Group"]]) %>
          <%= f.submit "検索", class: "big_btn" %>
        <%end%>
      </div>

      <div class="group_button">
        <%= link_to groups_path, class: "edit_link" do %>
          <div class="green_btn">グループ一覧</div>
        <%end%>
        <%= link_to new_group_path, class: "edit_link" do %>
          <div class="green_btn">グループ作成</div>
        <%end%>
      </div>

    </div>

    <div class="contact">
      <%= link_to "お問い合わせはこちら", new_contact_path %>
    </div>
  </div>
</div>