config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "homes#top", as: "root"
  post '/homes/guest_sign_in' => 'homes#guest_sign_in'
  patch "/users/:id/secession" => "users#secession", as: "secession"



  resources :users, only:[:show, :edit, :update]
  
  get "search" => "searches#search"
  get "my_group" => "groups#my_group"
  get "quick_form" => "users#quick_form"
  post "all_create" => "targets#all_create"

  resources :groups do
    resources :group_members, only: [:create, :destroy, :index] do
      member do
        post :direct
      end
    end
    resources :entries, only: [:create, :index, :destroy]
    resources :targets, only: [:create, :edit, :update, :destroy] do

    end
    resources :results, only: [:create, :edit, :update, :destroy]
    resources :group_messages, only: [:create, :destroy]
    resources :stamps, only: [:create, :destroy]
  end

  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :group, optional: true

  validates :user_id, presence: true
  validates :group_id, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  attachment :image
  enum group_type: {"work_group": 0, "friend_group": 1}
  validates :name, presence: true
  validates :group_type, presence: true

  has_many :group_members, dependent: :destroy
  has_many :users, through: :group_members
  has_many :entries, dependent: :destroy
  has_many :targets, dependent: :destroy
  has_many :group_messages, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :stamps, dependent: :destroy



  def user_exists?(user, group)
    group_members.where(user_id: user.id, group_id: group.id).present?
  end

  # 検索機能、名前が一致している部分があるgroupを返す
  def self.looks(word)
    @user = Group.where("name LIKE?","%#{word}%")
  end

  def entry_exists?(user)
    self.entries.find_by(group_id: self.id, user_id: user.id)
  end


  # users/quick_formにて使用
  def today_my_target_exists?(user)
    self.targets.find_by(user_id: user, created_at: Time.zone.now.all_day).present?
  end

  def today_my_target(user)
    self.targets.find_by(user_id: user, created_at: Time.zone.now.all_day)
  end

  def today_my_result_exists?(user)
    self.results.find_by(user_id: user, created_at: Time.zone.now.all_day).present?
  end

  def today_my_result(user)
    self.results.find_by(user_id: user, created_at: Time.zone.now.all_day)
  end

end

app/models/group_member.rb
class GroupMember < ApplicationRecord

  validates :user_id, presence: true
  validates :group_id, presence: true
  validates :operation_right, presence: true

  belongs_to :user
  belongs_to :group

end

app/models/group_message.rb
class GroupMessage < ApplicationRecord

  validates :user_id, presence: true
  validates :group_id, presence: true
  validates :message, presence: true

  belongs_to :user
  belongs_to :group
  has_many :stamps, dependent: :destroy

  def stamp_exists?(user, message)
    Stamp.where(user_id: user, group_message_id: message).present?
  end

  def stamp1_exists?(user, message)
    Stamp.where(user_id: user, group_message_id: message, choose_stamp: 1).present?
  end

  def stamp2_exists?(user, message)
    Stamp.where(user_id: user, group_message_id: message, choose_stamp: 2).present?
  end

  def stamp3_exists?(user, message)
    Stamp.where(user_id: user, group_message_id: message, choose_stamp: 3).present?
  end

  def stamp_count1
    self.stamps.where(choose_stamp: 1)
  end

  def stamp_count2
    self.stamps.where(choose_stamp: 2)
  end

  def stamp_count3
    self.stamps.where(choose_stamp: 3)
  end

end

app/models/result.rb
class Result < ApplicationRecord

  validates :user_id, presence: true
  validates :group_id, presence: true
  validates :target_id, presence: true
  validates :achievement, numericality: {less_than_or_equal_to: 100}
  validates :result_memo, length: {maximum: 50}


  belongs_to :target
  belongs_to :user
  belongs_to :group

  def self.chart_date
    order(created_at: :asc).pluck("created_at", "achievement").to_h
  end

end

app/models/stamp.rb
class Stamp < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :group_message

end

app/models/target.rb
class Target < ApplicationRecord

  validates :user_id, presence: true
  validates :group_id, presence: true
  validates :target_content, presence: { message: ""}, length: {maximum: 100}

  belongs_to :user
  belongs_to :group
  has_one :result, dependent: :destroy

  def target_exists?
    self.where(user_id: current_user.id).present?
  end


  # resultが投稿されたか調べる。
  def achievement_exists?(target, current_user)
    result = Result.find_by(target_id: target.id)
    # targetに紐づくresultはあるか
    if result.present?
      # 対象のresultは自分が投稿したものか
      if result.user.id == current_user
        # 自分のresultである
        return "my_result"
      else
        # 誰かのresultである
        return "someones_result"
      end
    else
      # 紐づくresultが未投稿
      if target.user_id == current_user
        # 自分のtargetであり、result未投稿
        return "my_target_yet_result"
      else
        # 誰かのtargetであり、result未投稿
        return "someones_target_yet_result"
      end
    end
  end

  # 対象のリザルトが投稿されていて、かつメモが空欄でないか。でなければfalseを返す
  def result_memo_exists?(target)
    Result.where.not(result_memo: nil || "").find_by(target_id: target.id).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  validates :email, presence: true
  validates :name, presence: true, length: { maximum: 10 }
  validates :intro, length: { maximum: 50 }


  has_many :group_members, dependent: :destroy
  has_many :groups, through: :group_members
  has_many :entry, dependent: :destroy
  has_many :targets, dependent: :destroy
  has_many :group_messages, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :stamps, dependent: :destroy


  # 検索機能、名前が一致している部分があるuserを返す
  def self.looks(word)
    @user = User.where("name LIKE?","%#{word}%")
  end

  # 退会ユーザー利用不可処理で用いる
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/stamps_helper.rb
module StampsHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <div class="error_messages"><%= message %></div>
    <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div>Copyright © Work Friend All Rights Reserved.</div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="logo"></div>

  <% if user_signed_in? %>
    <ul class="menu">
      <%= link_to my_group_path, class: "edit_link" do %>
        <li class="green_btn">マイグループ</li>
      <%end%>
      <%= link_to user_path(current_user.id), class: "edit_link" do %>
        <li class="green_btn">マイページ</li>
      <%end%>
      <%= link_to root_path ,class: "edit_link" do %>
        <li class="green_btn">TOP</li>
      <%end%>
      <%= link_to destroy_user_session_path, method: :delete, class: "edit_link" do %>
        <li class="green_btn">ログアウト</li>
      <%end%>
    </ul>

  <% else %>
    <ul class="menu">
      <%= link_to new_user_registration_path, class: "edit_link" do %>
        <li class="green_btn">新規登録</li>
      <%end%>
      <%= link_to new_user_session_path, class: "edit_link" do %>
        <li class="green_btn">ログイン</li>
      <%end%>
      <%= link_to root_path ,class: "edit_link" do %>
        <li class="green_btn">TOP</li>
      <%end%>
      <%= link_to  homes_guest_sign_in_path, method: :post, class: "sign_in edit_link" do %>
        <li class="green_btn">ゲスト</li>
      <%end%>
    </ul>
  <%end%>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkFriend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <%= yield %>

    <%= render "layouts/footer" %>

  </body>
</html>